### ISSUE TITLE
Stackoverflow on long cypher create query.

### ISSUE THREAD

**Issue by jmatsushita** [structr/structr#160]
Hi there,

http://gist.neo4j.org/?bb29230790bad3359a14

I created a dump from neo4j 2.1 with the neo4j-shell and tried to import this in Structr with the Schema importer. It has about 2500 statements (more than 1000 nodes). In both structr (1.0.0-RC2) and gist.neo4j.org it generates very similar stackoverflow error:

I've posted [an issue on the neo4j tracker](https://github.com/neo4j/neo4j/issues/2495).

In structr:
```
java.lang.StackOverflowError
	at org.neo4j.cypher.internal.compiler.v2_0.ReattachAliasedExpressions$.apply(ReattachAliasedExpressions.scala:31)
	at org.neo4j.cypher.internal.compiler.v2_0.ReattachAliasedExpressions$$anonfun$2.apply(ReattachAliasedExpressions.scala:34)
	at org.neo4j.cypher.internal.compiler.v2_0.ReattachAliasedExpressions$$anonfun$2.apply(ReattachAliasedExpressions.scala:34)
	at scala.Option.map(Option.scala:145)
	at org.neo4j.cypher.internal.compiler.v2_0.ReattachAliasedExpressions$.apply(ReattachAliasedExpressions.scala:34)
	at org.neo4j.cypher.internal.compiler.v2_0.ReattachAliasedExpressions$$anonfun$2.apply(ReattachAliasedExpressions.scala:34)
	at org.neo4j.cypher.internal.compiler.v2_0.ReattachAliasedExpressions$$anonfun$2.apply(ReattachAliasedExpressions.scala:34)
	at scala.Option.map(Option.scala:145)
```

Is there a way to change the embedded database configuration to allow it to process this import? Would be great to have examples of data imports (and medium to large sized ones as well) in the documentation as well!

Jun

**Comment by amorgner** [comment]
Structr is on 2.2 now, closing this.
