### ISSUE TITLE
Schema Sync fails behind reverse proxy

### ISSUE THREAD

**Issue by jmatsushita** [structr/structr#168]
Hi there,

I think this might be related to the nginx reverse proxy configuration of my server instance and I haven't tried between server instances, but when I ask my local structr instance to retrieve a schema from my server instance, it displays "2 out of 3 objects transferred", then "Authentication failed".

The local log says :
```
Jun 19, 2014 1:06:20 AM org.structr.cloud.CloudConnection <init>
INFO: New connection from structr.openoil.iilab.org/148.251.84.4:80
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90)
	at org.structr.cloud.CloudConnection.start(CloudConnection.java:114)
	at org.structr.cloud.CloudService.doRemote(CloudService.java:157)
	at org.structr.websocket.command.ListRemoteSyncablesCommand.processMessage(ListRemoteSyncablesCommand.java:74)
	at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:191)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:127)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:121)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:169)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:302)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:210)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:219)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:257)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.read(AbstractWebSocketConnection.java:500)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:409)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:745)
```

Is there a workaround to import/export schemas between structr instances or just to save the Schema when moving between different versions of Structr for testing purposes as I'm doing?

**Comment by amorgner** [comment]
As the reported error is likely due to network issues, and there's a workaround described above, I'm closing this.
