### ISSUE TITLE
Surface error messages about import in the Web UI 

### ISSUE THREAD

**Issue by jmatsushita** [structr/structr#175]
When importing this Gist: https://gist.githubusercontent.com/jmatsushita/28534761b0ad3d485a03/raw/691ec346e6265fab0a0e9f71497dcad51c1053a8/OpenOil-Structr

I get the following error message in the log. Would be great if this showed the error message on the Web UI and maybe a line where the error occured? Would be great for debugging. 

```
WARNING: No resource access object found for maintenance
Can't create `company` with properties or labels here. It already exists in this context
	at org.neo4j.cypher.internal.compiler.v2_0.pipes.NoLushEntityCreation$class.org$neo4j$cypher$internal$compiler$v2_0$pipes$NoLushEntityCreation$$failOn(ExecuteUpdateCommandsPipe.scala:127)
	at org.neo4j.cypher.internal.compiler.v2_0.pipes.NoLushEntityCreation$$anonfun$assertNothingIsCreatedWhenItShouldNot$1$$anonfun$apply$4.apply(ExecuteUpdateCommandsPipe.scala:117)
	at org.neo4j.cypher.internal.compiler.v2_0.pipes.NoLushEntityCreation$$anonfun$assertNothingIsCreatedWhenItShouldNot$1$$anonfun$apply$4.apply(ExecuteUpdateCommandsPipe.scala:113)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.neo4j.cypher.internal.compiler.v2_0.pipes.NoLushEntityCreation$$anonfun$assertNothingIsCreatedWhenItShouldNot$1.apply(ExecuteUpdateCommandsPipe.scala:112)
	at org.neo4j.cypher.internal.compiler.v2_0.pipes.NoLushEntityCreation$$anonfun$assertNothingIsCreatedWhenItShouldNot$1.apply(ExecuteUpdateCommandsPipe.scala:108)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.neo4j.cypher.internal.compiler.v2_0.pipes.NoLushEntityCreation$class.assertNothingIsCreatedWhenItShouldNot(ExecuteUpdateCommandsPipe.scala:107)
	at org.neo4j.cypher.internal.compiler.v2_0.pipes.NoLushEntityCreation$class.$init$(ExecuteUpdateCommandsPipe.scala:82)
	at org.neo4j.cypher.internal.compiler.v2_0.pipes.ExecuteUpdateCommandsPipe.<init>(ExecuteUpdateCommandsPipe.scala:32)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.builders.UpdateActionBuilder.apply(UpdateActionBuilder.scala:38)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.Phase$class.apply(Phase.scala:37)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.ExecutionPlanBuilder$$anon$3.apply(ExecutionPlanBuilder.scala:216)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.Phase$$anon$1.apply(Phase.scala:54)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.Phase$$anon$1.apply(Phase.scala:53)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.Phase$$anon$1.apply(Phase.scala:53)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.ExecutionPlanBuilder.buildQuery(ExecutionPlanBuilder.scala:82)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.ExecutionPlanBuilder.buildPipes(ExecutionPlanBuilder.scala:56)
	at org.neo4j.cypher.internal.compiler.v2_0.executionplan.ExecutionPlanBuilder.build(ExecutionPlanBuilder.scala:40)
	at org.neo4j.cypher.internal.compiler.v2_0.CypherCompiler$$anonfun$prepare$1.apply(CypherCompiler.scala:46)
	at org.neo4j.cypher.internal.compiler.v2_0.CypherCompiler$$anonfun$prepare$1.apply(CypherCompiler.scala:40)
	at org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:34)
	at org.neo4j.cypher.internal.CypherCompiler$VersionProxy$$anonfun$1.apply(CypherCompiler.scala:47)
	at org.neo4j.cypher.internal.CypherCompiler$VersionProxy$$anonfun$1.apply(CypherCompiler.scala:47)
	at org.neo4j.cypher.internal.compiler.v2_0.CypherCompiler.prepare(CypherCompiler.scala:40)
	at org.neo4j.cypher.internal.CypherCompiler$VersionProxy.prepare(CypherCompiler.scala:63)
	at org.neo4j.cypher.ExecutionEngine$$anonfun$3.apply(ExecutionEngine.scala:84)
	at org.neo4j.cypher.ExecutionEngine$$anonfun$3.apply(ExecutionEngine.scala:82)
	at org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:34)
	at org.neo4j.cypher.ExecutionEngine.prepare(ExecutionEngine.scala:82)
	at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:59)
	at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:54)
	at org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:65)
	at org.structr.schema.importer.SchemaImporter.importCypher(SchemaImporter.java:126)
	at org.structr.schema.importer.GraphGistImporter.execute(GraphGistImporter.java:70)
	at org.structr.rest.resource.MaintenanceResource.doPost(MaintenanceResource.java:109)
	at org.structr.rest.servlet.JsonRestServlet.doPost(JsonRestServlet.java:775)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:351)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:462)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:745)
Jun 25, 2014 7:26:08 PM org.structr.core.graph.BulkRebuildIndexCommand execute
```

**Comment by amorgner** [comment]
The schema importer was heavily revamped in mid-2015, so closing this old issue. @jmatsushita if you're still experiencing odd behaviour, please open a new issue.
