### ISSUE TITLE
Receive error on registration action when user has onCreate method defined that sends mail

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#289]
Shouldn't make a difference here, but I've made eMail mandatory for the User Entity.

Per Structr Team Guidance, 

Created two Mail Templates:

NEW_USER_WELCOME_SUBJECT
```
Hi there ${this.eMail}
```
and

NEW_USER_WELCOME_BODY
```
thanks for joining ${this.eMail}, please confirm your account

http://vm-2/confirm_registration?key=${this.confirmationKey}&target=register_thanks&onerror=register_error
```
The following is the the code for the onCreate method on User
```
(
send_plaintext_mail(
 "welcome@example.com", 
 "Example Team", 
 this.eMail, 
 this.eMail, 
 template("NEW_USER_WELCOME_SUBJECT", "en_US", this), 
template("NEW_USER_WELCOME_BODY", "en_US", this)),
set(this, "visibleToAuthenticatedUsers", "true")
)
```

When using the CRUD interface to add data (user), emails are sent immediately (templating stings are also rendered/substituted correctly).  additionally, values manipulated in subsequent (to send email) clause(s) are evaluated correctly..  Deliveries are as expected.  

However submission through registration page (constructed per security tutorial)
```
              <form action="javascript:void(0)" role="form" data-hash="abea525e">
                <fieldset data-hash="ce4b1bbe">
                  <div class="form-group" data-hash="3bdf9ae4">
                    <input autofocus="" name="eMail" placeholder="your email address" class="form-control" data-structr-name="eMail" data-hash="2382ccc0">
                  </div><!-- Change this to a button or input when using this as a form --><a href="javascript:void(0)" class="btn btn-lg btn-success btn-block" data-structr-action="registration" data-structr-attributes="eMail" data-structr-reload="false" data-structr-return="index" data-hash="f0f82463">Sign Up</a>
                </fieldset>
              </form>
```
produces the following error output

log output:
```
org.apache.commons.mail.EmailException: Invalid message supplied
        at org.apache.commons.mail.SimpleEmail.setMsg(SimpleEmail.java:47)
        at org.structr.common.MailHelper.sendSimpleMail(MailHelper.java:73)
        at org.structr.core.parser.Functions$72.apply(Functions.java:2477)
        at org.structr.core.parser.FunctionExpression.evaluate(FunctionExpression.java:57)
        at org.structr.core.parser.GroupExpression.evaluate(GroupExpression.java:39)
        at org.structr.core.parser.RootExpression.evaluate(RootExpression.java:36)
        at org.structr.core.parser.Functions.evaluate(Functions.java:293)
        at org.structr.schema.SchemaHelper.replaceVariables(SchemaHelper.java:812)
        at org.structr.core.entity.AbstractNode.replaceVariables(AbstractNode.java:1072)
        at org.structr.schema.action.Actions.execute(Actions.java:67)
        at org.structr.dynamic.User.onCreation(User.java:54)
        at org.structr.core.graph.GraphObjectModificationState.doInnerCallback(GraphObjectModificationState.java:227)
        at org.structr.core.graph.ModificationQueue.doInnerCallbacks(ModificationQueue.java:80)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:95)
        at org.structr.core.graph.Tx.success(Tx.java:68)
        at org.structr.rest.servlet.JsonRestServlet.doPost(JsonRestServlet.java:753)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
        at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:351)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
```

guidance appreciated

**Comment by cmorgner** [comment]
Hi, is there an update on this?

Can you share some more details, or how you fixed the issue? :)

**Comment by eric-schleicher** [comment]
I was never able to the get the plain text version to work... sending the rich text version did.

Closing since workaround was sasifactory
