### ISSUE TITLE
Sync Page from remote server fails

### ISSUE THREAD

**Issue by zzkozak** [structr/structr#313]
I set up two instances of structr 1.1-SNAPSHOT on two different server. I imported a page into server 1 and wanted to sync it on server 2.

The ui tells that the authentication has failed, but I used the right credentials (admin|admin).

Log outputs ...

Target server 2:
```
2015-01-07 17:08:03.374:WARN:oejh.HttpParser:qtp15608437-1082: badMessage: 400 Illegal character for HttpChannelOverHttp@1ea368b{r=0,a=IDLE,uri=-}
```
Source server 1:
```
Jan 07, 2015 5:12:03 PM org.structr.cloud.CloudConnection <init>
INFO: New connection from /172.16.12.221:8082
java.util.zip.ZipException: Not in GZIP format
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78)
        at org.structr.cloud.CloudConnection.start(CloudConnection.java:131)
        at org.structr.cloud.CloudService.doRemote(CloudService.java:174)
        at org.structr.websocket.command.ListRemoteSyncablesCommand.processMessage(ListRemoteSyncablesCommand.java:74)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:207)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:127)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:121)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:169)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:302)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:210)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:219)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:257)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.read(AbstractWebSocketConnection.java:500)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:409)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:722)
```

**Comment by cmorgner** [comment]
Hi,

please note that the target port for the synchronization service is
configured in the structr.conf configuration file. The default port is
54555, which is a different port than the HTTP / REST port for the
Structr Backend!

Please try again with port 54555!

Best,
Christian




Am 07.01.2015 um 17:19 schrieb zzkozak:
>
> I set up two instances of structr 1.1-SNAPSHOT on two different
> server. I imported a page into server 1 and wanted to sync it on server 2.
>
> The ui tells that the authentication has failed, but I used the right
> credentials (admin|admin).
>
> Log outputs ...
>
> Target server 2:
> 2015-01-07 17:08:03.374:WARN:oejh.HttpParser:qtp15608437-1082:
> badMessage: 400 Illegal character for HttpChannelOverHttp@1ea368b
> <https://github.com/HttpChannelOverHttp/structr/commit/1ea368b>{r=0,a=IDLE,uri=-}
>
> Source server 1:
> Jan 07, 2015 5:12:03 PM org.structr.cloud.CloudConnection
> INFO: New connection from /172.16.12.221:8082
> java.util.zip.ZipException: Not in GZIP format
> at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
> at java.util.zip.GZIPInputStream.(GZIPInputStream.java:78)
> at org.structr.cloud.CloudConnection.start(CloudConnection.java:131)
> at org.structr.cloud.CloudService.doRemote(CloudService.java:174)
> at
> org.structr.websocket.command.ListRemoteSyncablesCommand.processMessage(ListRemoteSyncablesCommand.java:74)
> at
> org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:207)
> at
> org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:127)
> at
> org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
> at
> org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
> at
> org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:121)
> at
> org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:169)
> at
> org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:302)
> at
> org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:210)
> at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:219)
> at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:257)
> at
> org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.read(AbstractWebSocketConnection.java:500)
> at
> org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:409)
> at
> org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
> at
> org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
> at
> org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
> at java.lang.Thread.run(Thread.java:722)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/structr/structr/issues/313>.
>


-- 
Christian Morgner
CTO Structr (c/o Morgner UG) · Hanauer Landstr. 291a · 60314 Frankfurt · Germany
Phone:   +49 163 2536088
Twitter: @cmor_

http://structr.com

**Comment by zzkozak** [comment]
Christian, you're right, now it works. I should RTFM! (http://docs.structr.org/#Data Sync)

**Comment by cmorgner** [comment]
Hi, can you please close this issue if it is resolved?!

Thank you and best regards,
Christian
