### ISSUE TITLE
Import of remote web page causes ClassCastExecption

### ISSUE THREAD

**Issue by grimace** [structr/structr#365]
I've tried this on a number of pages, some elements are imported and some fail with this stacktrace:

`2015-05-22 19:21:05.466:WARN:osw.StructrWebSocket:qtp944075145-30: Unhandled Error (closing connection)
java.lang.ClassCastException: org.structr.dynamic.File cannot be cast to org.structr.web.entity.Folder
	at org.structr.web.common.FileHelper.createFolderPath(FileHelper.java:671)
	at org.structr.web.Importer.downloadFile(Importer.java:850)
	at org.structr.web.Importer.createChildNodes(Importer.java:548)
	at org.structr.web.Importer.createChildNodes(Importer.java:719)
	at org.structr.web.Importer.createChildNodes(Importer.java:719)
	at org.structr.web.Importer.createChildNodes(Importer.java:502)
	at org.structr.web.Importer.readPage(Importer.java:296)
	at org.structr.websocket.command.ImportCommand.processMessage(ImportCommand.java:77)
	at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:204)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)`

this is the info for the path that Importer was processing:
`INFO: Download URL: http://mediterrasian.com/blog/wp-content/uploads/headway/cache/general-0ac1937.css?ver=4.1.1, address: http://mediterrasian.com/blog/?p=3391, cleaned address: http://mediterrasian.com/blog
May 22, 2015 7:21:20 PM org.structr.web.Importer downloadFile
INFO: Relative path: /wp-content/uploads/headway/cache/general-0ac1937.css?ver=4.1.1, final path: mediterrasian.com/blog/wp-content/uploads/headway/cache/
2`

**Comment by amorgner** [comment]
What was the root URL of the page you tried to import? http://mediterrasian.com/blog/?p=3391 ?

**Comment by amorgner** [comment]
This bug should be fixed with https://github.com/structr/structr/commit/70abc5bbff8270610fe096b583992254c3085c24.
