### ISSUE TITLE
Receive peculiar warning about neo version(s).

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#381]
When editing values in a view on an prexisting entity, i observed the following warning occur more than once.

This issue is Informational as it does not appear to have prevented the operation from succeeding.

The Neo Store being used here was created by structr many moons ago.

```
2015-08-10 16:13:26.599:WARN:oejs.ServletHandler:qtp83681118-53: /db/manage/server/version/
java.lang.IllegalStateException: The Neo Server running is of unknown type. Valid types are Community, Advanced, and Enterprise.
        at org.neo4j.server.rest.management.VersionAndEditionService.neoServerEdition(VersionAndEditionService.java:94)
        at org.neo4j.server.rest.management.VersionAndEditionService.getVersionAndEditionData(VersionAndEditionService.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by cmorgner** [comment]
Hi Eric,

this is a know issue caused by the Neo4jService component in Structr. You can get rid of this message by removing the Neo4jService from the list of configured services in structr.conf, but that will of course disable the Neo4j browser that is currently embedded into Structr. We have not yet found a solution for the issue because the startup process for an embedded Neo4j browser has changed / been deprecated.

Best,
Christian



Am 10.08.2015 um 19:29 schrieb Eric Schleicher:
>
> When editing values in a view on an prexisting entity, i observed the following warning occur more than once.
>
> This issue is Informational as it does not appear to have prevented the operation from succeeding.
>
> The Neo Store being used here was created by structr many moons ago.
>
> |2015-08-10 16:13:26.599:WARN:oejs.ServletHandler:qtp83681118-53: /db/manage/server/version/
> java.lang.IllegalStateException: The Neo Server running is of unknown type. Valid types are Community, Advanced, and Enterprise.
>          at org.neo4j.server.rest.management.VersionAndEditionService.neoServerEdition(VersionAndEditionService.java:94)
>          at org.neo4j.server.rest.management.VersionAndEditionService.getVersionAndEditionData(VersionAndEditionService.java:62)
>          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>          at java.lang.reflect.Method.invoke(Method.java:606)
>          at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
>          at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
>          at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
>          at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)
>          at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
>          at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
>          at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
>          at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
>          at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
>          at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
>          at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
>          at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
>          at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
>          at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
>          at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
>          at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>          at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
>          at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
>          at org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120)
>          at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
>          at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>          at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
>          at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
>          at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>          at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>          at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
>          at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>          at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
>          at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>          at org.eclipse.jetty.server.Server.handle(Server.java:497)
>          at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
>          at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
>          at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
>          at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
>          at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
>          at java.lang.Thread.run(Thread.java:745)
> |
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/structr/structr/issues/381>.
>


-- 
Christian Morgner
CTO Structr (c/o Morgner UG) · Hanauer Landstr. 291a · 60314 Frankfurt · Germany
Phone:   +49 163 2536088
Twitter: @cmor_

http://structr.com

**Comment by eric-schleicher** [comment]
Is it just a useless warning, or does it cause any problems.  I don't mind it in the log, just don't want anything to get mangles.

Given that i'm dealing with a data loss event, ust want to make sure i understand the behavior.

**Comment by cmorgner** [comment]
Judging from the code that creates the error message, I assume no functional impact, but I cannot guarantee anything.

See https://github.com/neo4j/neo4j/blob/2.3/community/server/src/main/java/org/neo4j/server/rest/management/VersionAndEditionService.java

**Comment by eric-schleicher** [comment]
I'll deal with it.  i use the Neo4j web  interface
