### ISSUE TITLE
NPE on resolving function property on attribute names: name

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#385]
I have an entity whose name value is set dynamically with a function property. 

My most recent log(s) are littered with the following exception:

```
INFO: No resource access grant found for signature _env.
Aug 17, 2015 4:47:39 PM org.structr.core.property.FunctionProperty getProperty
WARNING: Exception while evaluating function property name.
java.lang.NullPointerException
	at java.lang.String.concat(String.java:1970)
	at org.structr.core.property.FunctionProperty.getProperty(FunctionProperty.java:59)
	at org.structr.core.entity.AbstractNode.getProperty(AbstractNode.java:451)
	at org.structr.core.entity.AbstractNode.getProperty(AbstractNode.java:441)
	at org.structr.rest.serialization.StreamingWriter$RootSerializer.serialize(StreamingWriter.java:438)
	at org.structr.rest.serialization.StreamingWriter$RootSerializer.serialize(StreamingWriter.java:407)
	at org.structr.rest.serialization.StreamingWriter.stream(StreamingWriter.java:230)
	at org.structr.rest.servlet.JsonRestServlet.doGetOrHead(JsonRestServlet.java:862)
	at org.structr.rest.servlet.JsonRestServlet.doGet(JsonRestServlet.java:262)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.AsyncGzipFilter.doFilter(AsyncGzipFilter.java:408)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vigorouscoding** [comment]
This looks to me like you added a property called "name" to an entity and set its type to "Function".

if so please do the following:
- make sure there are no errors in that code (you can share it here if you like - its always a good idea to share the code responsible for errors)
- best rename that property to something else as "name" is a builtin property of Structr and changing the property type in inherited classes is not intended

**Comment by amorgner** [comment]
@eric-schleicher Any news here? Did you have the time to try what Kai suggested?

**Comment by eric-schleicher** [comment]
I checked, the structr script is error free  (It also works just fine).
The issue is an constant emission of NPEs in the log, but the system
behaves as expected.

I fully disagree with the second bullet point.  Inheritance should allow
for this type of atrribute to have a function set its display, but not
underlying value.  Especially since in this case the datatype isnt being
changed, just the method of how the value is displayed throughout the ui is
displayed.

This model is particulary useful fir entities are intermediate constructs
and dont have meaningful named, but get linked in the data ui.  Haveing the
function attribute allows for the name value to be namespaced

Eric

**Comment by vigorouscoding** [comment]
To me it does not look like it works just fine if it is throwing NullPointerExceptions - i would still be very interested to see the script itself and the conditions its being run in. Without this data this is very much a guessing game and I won't be able to help very much or in a coordinated way.

I also stand by my point of view that changing datatypes of properties (specifically system properties) in derived classes is problematic. you could override "id" to be a function property... or a boolean... and that would also (severly) impact the functionality.

I strongly suggest you create a support ticket under https://support.structr.com/ (if you dont want to share the code in this issue) and upload the much needed information so we can help you

**Comment by vigorouscoding** [comment]
Please retest this with the newest build - I just tested with the following code:

`name : FunctionProperty "concat('test', '123')"`

and got the result name = "test123" via REST and no NPE.

It seems this was fixed with commit https://github.com/structr/structr/commit/dc7ef52

**Comment by eric-schleicher** [comment]
I have not been getting these errors as of late.
