### ISSUE TITLE
Exception in POST: ClassCastException: java.lang.String cannot be cast to org.structr.core.graph.NodeInterface

### ISSUE THREAD

**Issue by HenningUhlig** [structr/structr#386]
Hi,

I get the following exception:

Aug 27, 2015 8:35:48 PM org.structr.rest.servlet.JsonRestServlet doPost
WARNUNG: Exception in POST
java.lang.ClassCastException: java.lang.String cannot be cast to org.structr.core.graph.NodeInterface
	at org.structr.core.property.EndNode.setProperty(EndNode.java:50)
	at org.structr.core.entity.AbstractNode.setPropertyInternal(AbstractNode.java:1043)
	at org.structr.core.entity.AbstractNode.setProperty(AbstractNode.java:1007)
	at org.structr.core.graph.CreateNodeCommand.execute(CreateNodeCommand.java:141)
	at org.structr.core.app.StructrApp.create(StructrApp.java:106)
	at org.structr.rest.resource.TypeResource.createNode(TypeResource.java:256)
	at org.structr.rest.resource.TypeResource.doPost(TypeResource.java:186)
	at org.structr.rest.servlet.JsonRestServlet.doPost(JsonRestServlet.java:425)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.AsyncGzipFilter.doFilter(AsyncGzipFilter.java:408)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

I can provide the Post Request and the Schema if you need.

Greetings,
Henning

**Comment by amorgner** [comment]
Could you please provide the exact build version?

I'm not exactly sure, but I think this was fixed recently. @cmorgner?

**Comment by HenningUhlig** [comment]
The problem occures in version: 1.1-SNAPSHOT build 19643 (201508201940)

**Comment by amorgner** [comment]
@HenningUhlig We'd appreciate if you could provide the details for us to reproduce the issue.

**Comment by amorgner** [comment]
Very old issue with no feedback provided, closing. Please re-open if still urgent.
