### ISSUE TITLE
Unable to import  backup from runniing maintentance/sync into fresh Structr Instance

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#391]
Hello, this is a follow on issue from the corrupt neo instances that i previously encountered.  

Working to get a basically trustworthy backup/restore regime into place and to make a more robust environment.  

Specifically looking to be able to use the maintentance/sync endpoint for full backup of critical graph/file/schema information on an adhoc basis when required.  This carries the (implicit) requirement to validate that I can successfully restore from one of these backups, which to date, I've not been able to accomplish.

The following is pertinent information on the steps taken to restore one of the zip files created through POSTing to the /maintenance/sync resource:

1. Post  to /structr/rest/maintentance/sync with JSON payload
```{"mode": "export", "file": "2015-09-14-export.zip"}```

2. See that file has successfully been created

3. Download/move file from the server to the target

4. Prep the target (in this case a vanilla ubuntu 14.04) install.
 - Follow the steps in sequence from the Dockerfile in Github that installed oracleJDK, etc.
 - Don't start the server

5. Copy the backup from landing folder to ```/usr/lib/structr-ui```, replacing the old seed.zip file.

6. Rename the imported file to seed.zip

7. Edit the /usr/lib/structr-ui/bin/config to alter startup setting: 
 - ```JAVA_OPTS="-server -d64 -Xms1g -Xmx2g -XX:MaxPermSize=256m -XX:+UseNUMA -XX:+UseConcMarkSweepGC"``` 
 - Default setting are insufficient to import the 36k relationships (the node coming fine, but runs out of memory) processing the store i'm using.  ```Xmx``` was changes to 2gb (vs default of 1gb).

8. ```sudo service structr-ui start```
 - Log available **[HERE](https://github.com/eric-schleicher/eric-schleicher.github.io/blob/master/logs-for-others/2015-09-14.import.as.seed.log.txt)** 
 - Logs show that that the seed file is found, it proceeds to import it.
 - Observe the following classes of unexpected/error like entries:
  - "<<" & ">>" are substitutions I've made here.  
 
     1. **WARNINGs** for what looks like for every single class in the Schema:
  
            ```WARNING: No instantiable class for relationship found for <<ENTITY>>  <<RELATIONSHIP_NAME>> <<Entity>>, returning generic relationship class.```
     2. **INFO** Messages like the Follwing:
	   ```
		Sep 14, 2015 10:53:34 AM org.structr.core.graph.SyncCommand importDatabase
		INFO: Imported 10,995 nodes and 2,405 rels, committing transaction..
		NOT creating relationship of type SYNC, start: 2e423e18fd9b4a9399e6d7cc3ca72017, end: 966a42f2d2384017870704448bb49624
	   ```

9. Process Completes with the follwing (expected) lines:

    ```
    Sep 14, 2015 10:54:54 AM org.structr.core.graph.SyncCommand importDatabaseINFO: Imported 10,995 nodes and 38,738 rels, committing transaction..
    ```

    ```
	Sep 14, 2015 10:54:54 AM org.structr.core.graph.SyncCommand importDatabase
    INFO: Import done in 135.660805767 s
	```

    ```
	Sep 14, 2015 10:55:02 AM org.structr.schema.compiler.NodeExtender compile
    INFO: Compiling 125 dynamic entities
    ```  

    - This implies that the node & relationships have been successfully imported, but that the schema also has successfully compiled.

10. Attempting to nagivate to the configured address:port results in a non-response.

11. Shut Down Structr-ui
  
  - ```sudo service structr-ui stop```

12. Rename the Seed file so that it's not imported again on restart (Doh! did this more than once)

13. Restart Structr-ui
	
	- ```sudo service structr-ui start```
	- Log available **[HERE](https://github.com/eric-schleicher/eric-schleicher.github.io/blob/master/logs-for-others/2015-09-14.post_import_restart.log.txt)**
	- Log show a dissapointing result there are are now only 11 Entities
	
		  ```INFO: Initialization complete ```
	
		  ```Sep 14, 2015 10:58:04 AM org.structr.schema.compiler.NodeExtender compile```

		  ```INFO: Compiling 11 dynamic entities``` 

**Hoping to get to the bottom of this and be able to restore using a similar method.**  It would appear that there is something going on (either in this schema or elsewhere) that is preventing this process from working correctly.  If It's an error in the steps, more than willing to change it.

Please Advise.

**Comment by cmorgner** [comment]
First of all: the import / export process using the sync command should be absolutely stable. We use this process all the time, for various tasks. If the seed.zip is a complete export of a given database, the import should reproduce the state of the database without errors.

Additionally, the seed import should only happen once, since there is a quite extensive check if there are already Structr nodes in the database. There should be no need to move the seed.zip out of the way!

Can you confirm that the number of EXPORTED nodes and relationships in the log file is the same as the number of IMPORTED nodes?

Which snapshot / version are you using?

Is there anything in the logfile AFTER "Compiling 125 dynamic entities"?

**Comment by eric-schleicher** [comment]
Glad to hear this is trusted functionality.  can't wait to share in the comfort of being able to use it :+1: 

@cmorgner , yes the is only being done on a fresh empty instance.

Ok I think I see what's happening now (regarding the expensive check).  

I've let this run and after 15 minutes or so, here is what comes after the "Compiling 125 dynamic entities";

```
Sep 14, 2015 12:54:01 PM org.structr.core.graph.ModificationQueue doValidation
INFO: 272,497 ms
java.lang.OutOfMemoryError: Java heap space
        at java.lang.ClassLoader.findLoadedClass0(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:1093)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:407)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.rollback(KernelTransactionImplementation.java:565)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:539)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:430)
        at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:95)
        at org.structr.core.graph.TransactionReference.close(TransactionReference.java:98)
        at org.structr.core.graph.TransactionCommand.finishTx(TransactionCommand.java:166)
        at org.structr.core.graph.Tx.close(Tx.java:79)
        at org.structr.core.graph.NodeService.importSeedFile(NodeService.java:371)
        at org.structr.core.graph.NodeService.initialized(NodeService.java:263)
        at org.structr.core.Services.initialize(Services.java:340)
        at org.structr.core.Services.initialize(Services.java:309)
        at org.structr.core.Services.getInstance(Services.java:146)
        at org.structr.Server.main(Server.java:36)
Sep 14, 2015 12:58:29 PM org.structr.core.Services initialize
WARNING: Exception while registering service NodeService: org.neo4j.graphdb.NotFoundException: org.neo4j.kernel.api.exceptions.EntityNotFoundException: Unable to load NODE with id 4856.
org.neo4j.graphdb.NotFoundException: org.neo4j.kernel.api.exceptions.EntityNotFoundException: Unable to load NODE with id 4856.
        at org.neo4j.kernel.impl.core.NodeProxy.hasProperty(NodeProxy.java:421)
        at org.structr.core.property.AbstractPrimitiveProperty.getProperty(AbstractPrimitiveProperty.java:72)
        at org.structr.core.entity.AbstractNode.getProperty(AbstractNode.java:451)
        at org.structr.core.entity.AbstractNode.getProperty(AbstractNode.java:436)
        at org.structr.web.entity.FileBase.getRelativeFilePath(FileBase.java:172)
        at org.structr.web.entity.FileBase.afterCreation(FileBase.java:127)
        at org.structr.core.graph.GraphObjectModificationState.doOuterCallback(GraphObjectModificationState.java:349)
        at org.structr.core.graph.ModificationQueue.doOuterCallbacks(ModificationQueue.java:137)
        at org.structr.core.graph.Tx.close(Tx.java:88)
        at org.structr.core.graph.NodeService.importSeedFile(NodeService.java:371)
        at org.structr.core.graph.NodeService.initialized(NodeService.java:263)
        at org.structr.core.Services.initialize(Services.java:340)
        at org.structr.core.Services.initialize(Services.java:309)
        at org.structr.core.Services.getInstance(Services.java:146)
        at org.structr.Server.main(Server.java:36)
Caused by: org.neo4j.kernel.api.exceptions.EntityNotFoundException: Unable to load NODE with id 4856.
        at org.neo4j.kernel.impl.api.store.PersistenceCache.getNode(PersistenceCache.java:135)
        at org.neo4j.kernel.impl.api.store.PersistenceCache.nodeGetProperty(PersistenceCache.java:401)
        at org.neo4j.kernel.impl.api.store.CacheLayer.nodeGetProperty(CacheLayer.java:262)
        at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeGetProperty(StateHandlingStatementOperations.java:751)
        at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeGetProperty(ConstraintEnforcingEntityOperations.java:281)
        at org.neo4j.kernel.impl.api.OperationsFacade.nodeGetProperty(OperationsFacade.java:219)
        at org.neo4j.kernel.impl.core.NodeProxy.hasProperty(NodeProxy.java:417)
        ... 14 more
Sep 14, 2015 12:58:29 PM org.structr.cron.CronService initialize
WARNING: No cron expression for task , ignoring.
Sep 14, 2015 12:58:29 PM org.structr.rest.service.HttpService initialize
INFO: Running in asynchronous mode
Sep 14, 2015 12:58:29 PM org.structr.agent.AgentService run
INFO: AgentService started
2015-09-14 12:58:35.717:INFO::main: Logging initialized @708375ms
Sep 14, 2015 12:58:36 PM org.structr.rest.service.HttpService initialize
INFO: Adding servlet org.structr.rest.servlet.JsonRestServlet-38b0f258@d194566e==org.structr.rest.servlet.JsonRestServlet,1,true for /structr/rest/*
Sep 14, 2015 12:58:36 PM org.structr.rest.service.HttpService initialize
INFO: Adding servlet org.structr.web.servlet.HtmlServlet-12811513@e1763451==org.structr.web.servlet.HtmlServlet,2,true for /structr/html/*
Sep 14, 2015 12:58:36 PM org.structr.rest.service.HttpService initialize
INFO: Adding servlet org.structr.websocket.servlet.WebSocketServlet-7a9c3fd9@a0aa3660==org.structr.websocket.servlet.WebSocketServlet,3,true for /structr/ws/*
Sep 14, 2015 12:58:36 PM org.structr.rest.service.HttpService initialize
INFO: Adding servlet org.structr.rest.servlet.CsvServlet-531602f4@b74aca79==org.structr.rest.servlet.CsvServlet,4,true for /structr/csv/*
Sep 14, 2015 12:58:36 PM org.structr.rest.service.HttpService initialize
INFO: Adding servlet org.structr.web.servlet.UploadServlet-7749df21@2c8852d==org.structr.web.servlet.UploadServlet,5,true for /structr/upload/*
Sep 14, 2015 12:58:36 PM org.structr.rest.service.HttpService startService
INFO: Starting Structr UI (host=0.0.0.0:8082, maxIdleTime=30000, requestHeaderSize=8192)
Sep 14, 2015 12:58:36 PM org.structr.rest.service.HttpService startService
INFO: Base path .
Sep 14, 2015 12:58:36 PM org.structr.rest.service.HttpService startService
INFO: Structr UI started at http://0.0.0.0:8082
2015-09-14 12:58:36.506:INFO:oejs.Server:main: jetty-9.2.9.v20150224
2015-09-14 12:58:36.988:INFO:/:main: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: loaded (conf ok)
2015-09-14 12:58:37.505:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@cb196dc{/,[file:/usr/lib/structr-ui/, jar:file:/usr/lib/structr-ui/lib/structr-rest-1.1-SNAPSHOT.jar!/],AVAILABLE}
2015-09-14 12:58:37.506:INFO:oejsh.ContextHandler:main: Started o.e.j.s.h.ContextHandler@5f274c06{/structr,null,AVAILABLE}
2015-09-14 12:58:37.521:INFO:oejs.ServerConnector:main: Started ServerConnector@53c44ce4{HTTP/1.1}{0.0.0.0:8082}
2015-09-14 12:58:37.522:INFO:oejs.Server:main: Started @710179ms
Sep 14, 2015 12:58:37 PM org.structr.files.ftp.FtpService startService
INFO: Starting FTP server on port 8021
12:58:44.813 [main] INFO  o.a.ftpserver.impl.DefaultFtpServer - FTP server started
Sep 14, 2015 12:58:44 PM org.structr.cloud.CloudService startService
INFO: CloudService successfully started.
Sep 14, 2015 12:58:44 PM org.structr.neo4j.Neo4jService startService
INFO: Starting Neo4j server on port 7474
2015-09-14 12:58:53.235:INFO:oejs.Server:main: jetty-9.2.9.v20150224
2015-09-14 12:58:53.441:INFO:oejsh.ContextHandler:main: Started o.e.j.s.h.MovedContextHandler@fbd14fd{/,null,AVAILABLE}
Sep 14, 2015 12:59:01 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
2015-09-14 12:59:08.813:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@b7a2358{/db/manage,null,AVAILABLE}
Sep 14, 2015 12:59:08 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
2015-09-14 12:59:16.270:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@31943b33{/db/data,null,AVAILABLE}
2015-09-14 12:59:16.436:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2ac8e211{/browser,jar:file:/usr/lib/structr-ui/lib/neo4j-browser-2.2.4.jar!/browser,AVAILABLE}
Sep 14, 2015 12:59:16 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
2015-09-14 12:59:16.973:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@38ac92a2{/,null,AVAILABLE}
2015-09-14 12:59:16.978:INFO:oejs.ServerConnector:main: Started ServerConnector@396de48d{HTTP/1.1}{0.0.0.0:7474}
2015-09-14 12:59:16.979:INFO:oejs.Server:main: Started @749637ms
Sep 14, 2015 12:59:16 PM org.structr.core.Services initialize
INFO: 7 service(s) processed
Sep 14, 2015 12:59:16 PM org.structr.core.Services initialize
INFO: Registering shutdown hook.
Sep 14, 2015 12:59:16 PM org.structr.core.Services initialize
INFO: Initialization complete
Sep 14, 2015 12:59:19 PM org.structr.schema.compiler.NodeExtender compile
INFO: Compiling 11 dynamic entities
Sep 14, 2015 12:59:23 PM org.structr.core.graph.ModificationQueue doValidation
INFO: 2,224 ms
```

so it looks like i need to allocate even more memory (than than the 2gb) will change the VM allocation and try with more.

**Comment by amorgner** [comment]
For a system like yours, I recommend 8 GB JVM heap at least.

**Comment by cmorgner** [comment]
Do you use Java 7 or 8? For a Java 7 JVM you might need to increase the PermGen space as well, the default is 64m iirc, a large schema will need at least 128m, better 256m.

Use `-XX:MaxPermSize=256m` for that!

**Comment by eric-schleicher** [comment]
Re: JDK, I've historically run Oracle 7 and in this case, using the meta install process outlined in the Docker File, which is also Oracle 7.

The default permgen set in the bin/config is 256m  I haven't changed that yet.  

I'm from running from a clean state again with 3gb of heap. @amorgner  We'll see how many GB it takes! :+1: 

If I import from the maintenance/sync with mode:Import does it run this same validation as coming in through the seed.zip?

Also: on this [page](https://docs.structr.org/REST-user-guide#Import And Export)
it makes mention of just pulling the schem over by clearing out the db file.  Has this changed?  when i open this in a text editor, it looks like a byte stream, not readible text.

**Comment by eric-schleicher** [comment]
@amorgner  & @cmorgner  It worked with the additional gb of heap.  the setting used to successfully import are 

```
JAVA_OPTS="-server -d64 -Xms2g -Xmx3g -XX:MaxPermSize=256m -XX:+UseNUMA -XX:+UseConcMarkSweepGC"
```

**Comment by amorgner** [comment]
Great! The only thing that beats RAM is more RAM. :-)
