### ISSUE TITLE
Repeating exception entries after updating to Snapshot  2.0-20151028.141112-2

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#408]
After updating to ```structr-ui-2.0-20151028.141112-2.deb```

I now see many of these exceptions being generated.  the system is however responsive and appears to work correctly.

please let me know if this execption could lead to data error and i will roll back to previous version.

```
java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:94)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:63)
	at org.structr.web.entity.dom.Content$ThreadLocalPegDownProcessor.initialValue(Content.java:772)
	at org.structr.web.entity.dom.Content$ThreadLocalPegDownProcessor.initialValue(Content.java:767)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.structr.web.entity.dom.Content$1.adapt(Content.java:103)
	at org.structr.web.entity.dom.Content$1.adapt(Content.java:97)
	at org.structr.web.entity.dom.Content.renderContent(Content.java:377)
	at org.structr.web.entity.dom.DOMNode.render(DOMNode.java:1292)
	at org.structr.web.entity.dom.DOMElement.renderContent(DOMElement.java:381)
	at org.structr.web.entity.dom.DOMNode.render(DOMNode.java:1292)
	at org.structr.web.entity.dom.DOMElement.renderContent(DOMElement.java:381)
	at org.structr.web.entity.dom.DOMNode.render(DOMNode.java:1292)
	at org.structr.web.entity.dom.DOMElement.renderContent(DOMElement.java:381)
	at org.structr.web.entity.dom.DOMNode.render(DOMNode.java:1292)
	at org.structr.web.entity.dom.DOMElement.renderContent(DOMElement.java:381)
	at org.structr.web.entity.dom.DOMNode.render(DOMNode.java:1292)
	at org.structr.web.entity.dom.DOMElement.renderContent(DOMElement.java:381)
	at org.structr.web.entity.dom.DOMNode.render(DOMNode.java:1292)
	at org.structr.web.entity.dom.DOMElement.renderContent(DOMElement.java:381)
	at org.structr.web.entity.dom.DOMNode.render(DOMNode.java:1292)
	at org.structr.web.entity.dom.DOMElement.renderContent(DOMElement.java:381)
	at org.structr.web.entity.dom.DOMNode.render(DOMNode.java:1292)
	at org.structr.web.entity.dom.Page.render(Page.java:758)
	at org.structr.web.servlet.HtmlServlet$1.run(HtmlServlet.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.MethodVisitor.<init>(MethodVisitor.java:86)
	at org.objectweb.asm.MethodVisitor.<init>(MethodVisitor.java:71)
	at org.objectweb.asm.tree.MethodNode.<init>(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.<init>(Unknown Source)
	at org.parboiled.transform.ClassNodeInitializer.visitMethod(ClassNodeInitializer.java:136)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:852)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:669)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
	at org.parboiled.transform.ClassNodeInitializer.process(ClassNodeInitializer.java:63)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:44)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	... 31 more
```

**Comment by amorgner** [comment]
This is a known error caused by conflicting versions of a specific library (asm). Depending on the order the JVM loads the libs, you see or don't see this error. We'll fix it asap.

The only consequence is that Structr is not able to render Markdown code to HTML in a Content node.

**Comment by eric-schleicher** [comment]
Thanks.   I'll update to next snap and e-check when available

This was with 2.0-20151028.141112-2.

**Comment by eric-schleicher** [comment]
@amorgner, fyi.  I just installed the 2.0 snapshot 3 and this is still present.

**Comment by amorgner** [comment]
@eric-schleicher Could you plese test with the current snapshot? We resolved all ambigous dependencies in late-2015.

**Comment by eric-schleicher** [comment]
I have not see recurrences of this in some time.  Closing
