### ISSUE TITLE
Failure to create Schema Snapshot from snapshots UI

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#429]
I recently created an extra size of thumbnail per instructions @amorgner provided in the google group.  

This change worked successfully and i haven't had any problems (backing up or restoring), however i can't generate a snapshot anymore.
#### from /var/log/structr-ui.log
```

instance id from getGlobalSetting: 5f6c4deb38324879ba2588a241001364
instance id: 5f6c4deb38324879ba2588a241001364
java.lang.IllegalStateException: Unknown type Thumbnail
        at org.structr.schema.export.StructrPropertyDefinition.deserialize(StructrPropertyDefinition.java:430)
        at org.structr.schema.export.StructrTypeDefinition.deserialize(StructrTypeDefinition.java:416)
        at org.structr.schema.export.StructrTypeDefinition.deserialize(StructrTypeDefinition.java:664)
        at org.structr.schema.export.StructrTypeDefinitions.deserialize(StructrTypeDefinitions.java:150)
        at org.structr.schema.export.StructrSchemaDefinition.deserialize(StructrSchemaDefinition.java:186)
        at org.structr.schema.export.StructrSchemaDefinition.initializeFromDatabase(StructrSchemaDefinition.java:302)
        at org.structr.schema.export.StructrSchema.createFromDatabase(StructrSchema.java:59)
        at org.structr.rest.maintenance.SnapshotCommand.createSnapshot(SnapshotCommand.java:106)
        at org.structr.rest.maintenance.SnapshotCommand.execute(SnapshotCommand.java:72)
        at org.structr.websocket.command.SnapshotsCommand.processMessage(SnapshotsCommand.java:95)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:204)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

```
Files are generated, but are of size empty (0  kb)

running version  2.0-SNAPSHOT build 57e9f (201601062321

Running a bit behind on builds since the file system uniqueness change.

**Comment by amorgner** [comment]
@eric-schleicher Could you please test with the latest snapshot? You can disable the file uniqueness with

    application.filesystem.unique.paths = false

See also https://support.structr.com/article/49.

**Comment by eric-schleicher** [comment]
Yes.  Will do it this week.

Is there a way to get a list of duplicates if the current filesystems isn't
conforming?

I want to have a process/approach to getting rid of duplicates.

Eric

**Comment by eric-schleicher** [comment]
Update:  I can't test this as i removed the additional thumbnail type from the model.  close?

**Comment by cmorgner** [comment]
I just tested the export / import roundtrip with a custom thumbnail and the format string `20, 20, true`, which successfully creates a third thumbnail of size 20x20 in each image.
