### ISSUE TITLE
Not restoring from schema snapshot if there's a Notion to dynamic property

### ISSUE THREAD

**Issue by l-1** [structr/structr#441]
As it says in a title. If there's Notion to static property, everything's fine. 
I even tested it with a clean db. I created class `Sample` and linked it to `SampleApplication` and created a dynamic property in `Sample` class: `Notion` to SampleApplication's `title` (`sa, _title`). It compiles ok and can be used in application but restoring from a snapshot isn't working.

Using 2.0-SNAPSHOT build 5616c (201603301445)

> WARNING: Unable to compile dynamic entity Sample: cannot find symbol
  symbol:   variable title
  location: class org.structr.dynamic.SampleApplication
Sample compiler_error cannot find symbol
  symbol:   variable title
  location: class org.structr.dynamic.SampleApplication
at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:118)
at org.structr.core.graph.Tx.success(Tx.java:69)
at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:206)
at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:745)

**Comment by vigorouscoding** [comment]
Thank you for reporting this! Accessing the property by its internal name is not really intended - Instead of accessing "_title" one should use "titleProperty". But this should not result in a broken schema export.

I just changed the behavior of the Schema Export so that usages like that will be changed to the preferred usage. Exporting your schema and re-importing it should result in "_title" being "titleProperty".

For reference this is the commit: https://github.com/structr/structr/commit/4fcc82609f8ac9f9c84b85f885a8418ece70b2b7

If you are using the master branch you can just pull the newest code - if you are using a snapshot you'll have to wait until the next snapshot. Usually this does not take very long.

**Comment by vigorouscoding** [comment]
Well - re-reading your comment tells me that you are using a snapshot... A new snapshot will be deployed soon. If you don't want to wait you could change your Notions by hand.

AND I accidentally closed the issue... I'll reopen it until we can verify that everything works as expected.

**Comment by l-1** [comment]
It works, thanks! And, yes, now it transforms "_title" to "titleProperty" on export.
