### ISSUE TITLE
Regression? System property `type` no longer editable (even with admin privs)

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#450]
I've discovered a new and very undesirable behavior change in the way that a specific system property is locked down.  I've just noticed this in snapshot build 5616c (201603301445).  I don't perform this (impacted) operation everyday, but on a recurring basis.  I'm allowing a user to upload a font through the the structr-ui web interface (filesystem UI and in-future FTP as well).  when these font files (ttf, woff, etc) file come to rest in Structr, the assets are of type "File".  In our model, Font extends File with additional attributes that allows for other information to be tracked along with the file..

This was previously achievable  (to change the type attribute of the file) from the either the edit dialog in the filesystem interface and through REST [PUT] by a highly entitled user (admin).  The net result is that changing a node's type attributes is now disallowed in it's entirety, including through REST as an admin : ( 

While the purpose of this is likely understandable, this behavior presumes that there isn't a valid reason for an asset to be presented to the system (in my case as entity of type 'file') and then subsequently be reclassified (in this case to entity of type 'Font'). 

At the moment these nodes *have* to be edited directly from neo4j, since Structr refuses to do so.  I'm sure this isn't the intention.

IIRC, a change was made to allow this behavior (in 2014/2015) and that this is a regression from the previously discussed & intended functionality.  I would argue that modifying the type attribute should be allowable by *an appropriate* authority level (presuming admin).

Conversely, If this type system property checking is to be left as is (to globally disallow), then some type of extension/mime/type/Structr Entity Type mapping should be exposed so that assets presented in the filesystem (/upload) interfaces can have a type mapping controllable by the user.

Additionally, if in-UI editing of type is to be depricated, then the UI should show the type as a read only property, which it doesn't in the filesystem edit dialog as shown in the following capture

![image](https://cloud.githubusercontent.com/assets/8261783/14802497/00bd8064-0b06-11e6-86d4-d88601a0be74.png)

As for our processes related to Entities that extend File that handles this, It's  trivial to upload from the names resource with imageData, and to explicitly set type on the upload endpoint, but if other tools are used, it's not possible to control this with any precision.

**Comment by amorgner** [comment]
There's a built-in function named `unlock_system_properties_once(node) `(see support article https://support.structr.com/article/403) which allows any admin user to modify a system property.

The intention is to make sure that changing a system property is a concious decision of a user within an admin context. Too many bad things can happen if you change the type of an object accidentially.

**Comment by eric-schleicher** [comment]
Is there a corresponding REST command that allows for this?

**Comment by amorgner** [comment]
There's no built-in REST command. The intended way is to to create a custom schema method with the `unlock_system_properties_once()` command in it.

**Comment by eric-schleicher** [comment]
This requires a custom method on any entity that might be reclassified.  is
there a more scaleable approach?

**Comment by eric-schleicher** [comment]
Really the most elegant solution in this case (types that inherit from file) is allowing a user controlled mapping to determine what an asset's resolved Type is based on the extension when it's uploaded.  this would provide a consistent method of uploading content into the CMS and having it get "typed" correctly.

**Comment by eric-schleicher** [comment]
Unfortunately trying to use the unlock_system_properties_once() causes the following error when added to a schema method on File.

```
(
unlock_system_properties_once(this),
set_privileged('File', 'type', 'Font')
)
```

```
java.lang.UnsupportedOperationException: Active save actions are not supported for overridable types.
        at org.structr.schema.SchemaHelper.formatDynamicSaveActions(SchemaHelper.java:902)
        at org.structr.core.entity.SchemaNode.getAuxiliarySource(SchemaNode.java:497)
        at org.structr.schema.SchemaService.reloadSchema(SchemaService.java:107)
        at org.structr.schema.SchemaHelper.reloadSchema(SchemaHelper.java:301)
        at org.structr.schema.ReloadSchema.execute(ReloadSchema.java:34)
        at org.structr.core.graph.ModificationQueue.doPostProcessing(ModificationQueue.java:127)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:115)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.rest.servlet.JsonRestServlet.doPost(JsonRestServlet.java:433)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.AsyncGzipFilter.doFilter(AsyncGzipFilter.java:408)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

if  this is just a usage pattern issue we can move it to the google group.

**Comment by eric-schleicher** [comment]
More context.  i was able to create a new Entity type and apply the method as outlined above and successfully test it...  So this error impacts Entity Type file, but not Entities of type `AbstractNode`

**Comment by eric-schleicher** [comment]
Closing this issue and opened a new of specifically for the error
