### ISSUE TITLE
Unable to ascertain reason for schema compilation failure performing snapshot restore

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#459]
I'm in the process of restoring a structr instance from a known good backup and update the schema to a slightly newer version.  The snapshot was created with the #Schema/Snapshots ->CreateSnapshot function.

The restore of the backup succeeds just fine, but after cycling the service (just for good measure) an attempt to restore the snapshot (from the Snapshots dialog) fails.

Same Structr Versions (2.0-SNAPSHOT build 5616c - 201603301445) for both the snapshot and the restored instance.  The schema models are also virtually identical (I only lost a little bit of work between the save of the snapshot and the backup).  I was hoping to use the restore button and be on my way.

that being said, I've never been able to successfully restore using this method, so it's unclear whether there is a underlying bug in the restore process, or whether this schema snapshot being created is in some way defective.  I can share the snapshot schema json file with the team, but wish not to post it here.

Regarding the Error, the logs show invalid notion property, however provides no clue as to which entity or properties are affected.

I've been deliberately and methodically keeping snapshots.json in my source control specifically for this scenario (to recover _just_ the schema; and with data from known good backup) but have not need to restore in this fashion.

Is there some way to determine what is causing the error? (bug in restore process vs defect in snapshot json)

log output below.

```
May 19, 2016 12:59:14 PM org.structr.schema.SchemaService reloadSchema
SEVERE: Unable to compile dynamic schema.
SchemaNode invalid_property_definition Invalid notion property expression.
        at org.structr.schema.parser.NotionPropertyParser.parseFormatString(NotionPropertyParser.java:187)
        at org.structr.schema.parser.PropertySourceGenerator.getPropertySource(PropertySourceGenerator.java:78)
        at org.structr.schema.SchemaHelper.extractProperties(SchemaHelper.java:496)
        at org.structr.core.entity.SchemaNode.getSource(SchemaNode.java:223)
        at org.structr.schema.SchemaService.reloadSchema(SchemaService.java:105)
        at org.structr.schema.SchemaHelper.reloadSchema(SchemaHelper.java:301)
        at org.structr.schema.ReloadSchema.execute(ReloadSchema.java:34)
        at org.structr.core.graph.ModificationQueue.doPostProcessing(ModificationQueue.java:127)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:115)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:206)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

SchemaNode invalid_property_definition Invalid notion property expression.
        at org.structr.schema.parser.NotionPropertyParser.parseFormatString(NotionPropertyParser.java:187)
        at org.structr.schema.parser.PropertySourceGenerator.getPropertySource(PropertySourceGenerator.java:78)
        at org.structr.schema.SchemaHelper.extractProperties(SchemaHelper.java:496)
        at org.structr.core.entity.SchemaNode.getSource(SchemaNode.java:223)
        at org.structr.schema.SchemaService.reloadSchema(SchemaService.java:105)
        at org.structr.schema.SchemaHelper.reloadSchema(SchemaHelper.java:301)
        at org.structr.schema.ReloadSchema.execute(ReloadSchema.java:34)
        at org.structr.core.graph.ModificationQueue.doPostProcessing(ModificationQueue.java:127)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:115)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:206)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:118)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:206)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by eric-schleicher** [comment]
FWIW An attempt to restore a previous snapshot (from before the backup) also failed in identical fashion.

**Comment by amorgner** [comment]
Seems that a Notion Property expression could not be compiled. Please submit the schema JSON exported from the original system via our support system.

**Comment by eric-schleicher** [comment]
See: support ticket 37c18a1b8b194dd493197d65c5ae82d5

**Comment by eric-schleicher** [comment]
In looking at the Schema snapshot(s), it looks like the notion expression don't include the 'Property' suffix after non built-in attribute names.  Might this Error be occuring when the expression is being reapplied (perphaps without the needed "Property" suffix)?

**Comment by eric-schleicher** [comment]
Following up on this. very interested to understand the nature of the issue.

**Comment by eric-schleicher** [comment]
@amorgner, after much troubleshooting, I've been able to ascertain why producing this error on model with Notions.

It's related to how the the schema is exported for Entities' `SchemaRelationships` when there is no explicitly defined JSON Names.  Here is a video showing the difference between the schema snapshots generated for explicitly defined vs implicitly generated Remote Attribute JSON Names.

https://youtu.be/bn546rtQqnI

Essentially, for any Entity without explicitly defined JSON Names, Structr is Exporting invalid metadata,  creating incorrect properties in the snapshot output.  These invalid properties subsequently cannot be found (since they don't exist) when attempting to import the schema.

With some guidance, I may be able to contribute a fix but it's not clear whether the preferred approach is for structr to automatically instantiate relationships with explicit values (when relationships are ceated), or whether the team's preference is directly address the export work correctly (and continue to allow undefined JSON names).

**Comment by eric-schleicher** [comment]
bump..   I would like to help resolve this issue.

**Comment by eric-schleicher** [comment]
double bump. would like some guidance on how i may be able to contribute/resolve this.  The issue prevents applying schema changes made on one system to a different existing system (e.g. manage schema in a development system and apply it downstream).

**Comment by cmorgner** [comment]
@eric-schleicher your observation was 100% correct, there was an error in the JSON names generated for export. Commit 5815173f3fb18032a2f412458e0291e4d383d7e0 fixes this issue and adds three tests that check for the correctness of the export.

Please review and close this issue if resolved.

**Comment by constructive-realities** [comment]
You made my month.  thanks @cmorgner.  I also see new snapshots for 2.1.0 getting published.   truly great news.  I'll try and validate and close this week

**Comment by eric-schleicher** [comment]
You made my month. thanks @cmorgner. I also see new snapshots for 2.1.0 getting published. truly great news. I'll try and validate and close this week

**Comment by vigorouscoding** [comment]
I'll close this as there is a fix for this issue
