### ISSUE TITLE
Duplicate Relationships on creation of a related node

### ISSUE THREAD

**Issue by ryancollingwood** [structr/structr#474]
Structr Version: structr-ui-2.0.2-SNAPSHOT-201605181524.fd1d6

Full details and database copy available at: https://groups.google.com/forum/#!topic/structr/s8WYpejplDE

Error Log
`WARNING: Exception in PUT
java.lang.IllegalStateException: Unable to delete relationship[3521] since it is already deleted.
        at org.neo4j.kernel.impl.core.RelationshipProxy.delete(RelationshipProxy.java:163)
        at org.structr.neo4j.wrapper.RelationshipWrapper.delete(RelationshipWrapper.java:152)
        at org.structr.core.graph.DeleteRelationshipCommand.execute(DeleteRelationshipCommand.java:85)
        at org.structr.core.graph.DeleteRelationshipCommand.execute(DeleteRelationshipCommand.java:56)
        at org.structr.core.app.StructrApp.delete(StructrApp.java:153)
        at org.structr.core.entity.ManyStartpoint.set(ManyStartpoint.java:113)
        at org.structr.core.property.StartNodes.setProperty(StartNodes.java:177)
        at org.structr.core.property.StartNodes.setProperty(StartNodes.java:55)
        at org.structr.core.entity.AbstractNode.setPropertyInternal(AbstractNode.java:1442)
        at org.structr.core.entity.AbstractNode.setProperty(AbstractNode.java:1403)
        at org.structr.rest.resource.Resource.doPut(Resource.java:165)
        at org.structr.rest.servlet.JsonRestServlet.doPut(JsonRestServlet.java:606)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.AsyncGzipFilter.doFilter(AsyncGzipFilter.java:408)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

Sep 08, 2016 10:58:57 AM org.structr.rest.servlet.JsonRestServlet doPut
WARNING:
java.lang.IllegalStateException: Unable to delete relationship[3521] since it is already deleted.
        at org.neo4j.kernel.impl.core.RelationshipProxy.delete(RelationshipProxy.java:163)
        at org.structr.neo4j.wrapper.RelationshipWrapper.delete(RelationshipWrapper.java:152)
        at org.structr.core.graph.DeleteRelationshipCommand.execute(DeleteRelationshipCommand.java:85)
        at org.structr.core.graph.DeleteRelationshipCommand.execute(DeleteRelationshipCommand.java:56)
        at org.structr.core.app.StructrApp.delete(StructrApp.java:153)
        at org.structr.core.entity.ManyStartpoint.set(ManyStartpoint.java:113)
        at org.structr.core.property.StartNodes.setProperty(StartNodes.java:177)
        at org.structr.core.property.StartNodes.setProperty(StartNodes.java:55)
        at org.structr.core.entity.AbstractNode.setPropertyInternal(AbstractNode.java:1442)
        at org.structr.core.entity.AbstractNode.setProperty(AbstractNode.java:1403)
        at org.structr.rest.resource.Resource.doPut(Resource.java:165)
        at org.structr.rest.servlet.JsonRestServlet.doPut(JsonRestServlet.java:606)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.AsyncGzipFilter.doFilter(AsyncGzipFilter.java:408)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by ryancollingwood** [comment]
Naively thinking that this fix may be related?
https://github.com/structr/structr/commit/6a3106b53993e9893e48e5bd767932e26f97e108

**Comment by cmorgner** [comment]
There is now a fix in the master branch that locks relationship creation and prevents the creation of duplicate relationships in the backend. Thanks for reporting this! The missing locking was triggered by a duplicate click handler in the backend Ui.

Please review and close if fixed!
Thank you!

**Comment by vigorouscoding** [comment]
I'll close this as it has been fixed for a while now. Please reopen if you find a way to reproduce the buggy behaviour and thanks for reporting this!
