### ISSUE TITLE
WebSocket Unhandled Error on FileSystem tab after creating 1 folder

### ISSUE THREAD

**Issue by ravensorb** [structr/structr#483]
I have a  clean install of structr using the structr-ui-2.1.0-20161126.214858-22 build. I log in, go to the files tab, create 1 folder and before I can even change the name, I get a "Connection Lost of timed out" error message with the following in the structr-ui.log file

```
2016-11-29 10:13:44.140:WARN:osw.StructrWebSocket:qtp2137535865-34: Unhandled Error (closing connection)
org.neo4j.driver.v1.exceptions.ClientException: Invalid input 'N': expected whitespace, comment, '.', node labels, '[', "=~", IN, STARTS, ENDS, CONTAINS, IS, '^', '*', '/', '%', '+', '-',
'=', "<>", "!=", '<', '>', "<=", ">=", AND, XOR, OR, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, CALL, RETURN, UNION, ';' or end of input (line 1, column 51 (offset: 50))|"MATCH (n:FileBase) WHERE n.`hasParent` = {param0} NOT  AND n.`isThumbnail` = {param1} RETURN DISTINCT n ORDER BY COALESCE(n.`name`, '')"|
                       ^
        at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:464)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:425)
        at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
        at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveOne(SocketConnection.java:143)
        at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.receiveOne(ConcurrencyGuardingConnection.java:164)
        at org.neo4j.driver.internal.pool.PooledConnection.receiveOne(PooledConnection.java:183)
        at org.neo4j.driver.internal.InternalStatementResult.tryFetchNext(InternalStatementResult.java:282)
        at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:160)
        at org.structr.bolt.SessionTransaction$StatementIterable$1.hasNext(SessionTransaction.java:388)
        at org.structr.api.util.Iterables$MapIterable$MapIterator.hasNext(Iterables.java:142)
        at org.structr.api.util.Iterables$MapIterable$MapIterator.hasNext(Iterables.java:142)
        at org.structr.api.util.Iterables.addAll(Iterables.java:38)
        at org.structr.api.util.Iterables.toList(Iterables.java:92)
        at org.structr.bolt.index.AbstractCypherIndex$CachedQueryResult.<init>(AbstractCypherIndex.java:199)
        at org.structr.bolt.index.CypherNodeIndex.getResult(CypherNodeIndex.java:64)
        at org.structr.bolt.index.AbstractCypherIndex.query(AbstractCypherIndex.java:154)
        at org.structr.core.graph.search.SearchCommand.doSearch(SearchCommand.java:204)
        at org.structr.core.graph.search.SearchCommand.getResult(SearchCommand.java:308)
        at org.structr.websocket.command.ListCommand.processMessage(ListCommand.java:106)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:208)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

Interestingly -- if I go to the "Data" tab, select "Folder" and delete the entry and then go back to the File System the error still continues to occur.

**Comment by cmorgner** [comment]
Hi, thanks for reporting this issue!

How did you get the structr-ui-2.1.0-20161126.214858-22 build? The latest snapshot on the website is 2.1.0-SNAPSHOT-201611262147.e3f49, so I'm wondering how you got that version.

Can you please try with the snapshot from https://structr.org/download or use the current master from GitHub? I just tested both the current master and the above snapshot, and the bug is not there.

**Comment by ravensorb** [comment]
I grabbed it from here

https://oss.sonatype.org/content/repositories/snapshots/org/structr/structr-ui/2.1.0-SNAPSHOT/

**Comment by cmorgner** [comment]
Please try a different one.

**Comment by vigorouscoding** [comment]
Does this error still occurr in the most recent snapshots? We did a lot in that area and I have not seen something like that in quite some time. I'll leave this open and add the "waiting for confirmation" tag

**Comment by vigorouscoding** [comment]
I'll close this as I believe this problem has been resolved - please reopen if you find a way to reproduce this behaviour consistently with the current master.
