### ISSUE TITLE
ClassCastException: org.structr.dynamic.Table cannot be cast to org.structr.web.entity.dom.DOMElementHi

### ISSUE THREAD

**Issue by hkollera-inovex** [structr/structr#492]
Hi, inserting a table into a page i get the following exception:

java.lang.ClassCastException: org.structr.dynamic.Table cannot be cast to org.structr.web.entity.dom.DOMElement
        at org.structr.web.entity.dom.Page.createElement(Page.java:320)
        at org.structr.web.Importer.createChildNodes(Importer.java:596)
        at org.structr.web.Importer.createChildNodes(Importer.java:724)
        at org.structr.web.Importer.createChildNodes(Importer.java:724)
        at org.structr.web.Importer.createChildNodes(Importer.java:724)
        at org.structr.web.Importer.createChildNodesWithHtml(Importer.java:281)
        at org.structr.web.Importer.parsePageFromSource(Importer.java:318)
        at org.structr.web.Importer.parsePageFromSource(Importer.java:303)
        at org.structr.websocket.command.SaveNodeCommand.processMessage(SaveNodeCommand.java:72)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:203)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

My Version of structr is: 2.0.1 from the debian package

**Comment by cmorgner** [comment]
Hi,

the error message indicates that you created a type named `Table` in your schema, which interferes with the internal table class, since only the simple name of a class is currently used for identification.

Best practice is to use a common prefix for your custom types, since a query would otherwise produce mixed results containing internal table class / HTML elements and your dynamic table entities.

Is that an acceptable solution for you?

Best,
Christian

**Comment by hkollera-inovex** [comment]
Not really, because I got the error, while trying to drop a table from the remote widgets onto the page. With lists etc. it runs smoothly, but not with tables.

**Comment by cmorgner** [comment]
So you did not create a `Table` entity in the schema?

**Comment by hkollera-inovex** [comment]
No, just tried to use the UI

**Comment by cmorgner** [comment]
Ok, I see. The new widgets are not compatible with the 2.0.1 version, please upgrade to 2.1-SNAPSHOT using https://oss.sonatype.org/content/repositories/snapshots/org/structr/structr-ui/2.1.0-SNAPSHOT/structr-ui-2.1.0-20170428.150432-27.deb

**Comment by hkollera-inovex** [comment]
Thanks, have a nice weekend
Harald
