### ISSUE TITLE
Problem adding HTML Element from context menu

### ISSUE THREAD

**Issue by bryonvaughn** [structr/structr#507]
Introduced in 2.1.2, and also present in the 2.1.3 snapshot:
Whenever I attempt to add an HTML Element through the context menu in the Structr interface, the screen flashes, and no element is added.  This occurs in both the pages and shared components panels.

The log error is below:
12:34:29.974 [qtp366752671-20] WARN  o.structr.websocket.StructrWebSocket - Unhandled Error (closing connection)
java.lang.NullPointerException: null
	at org.structr.websocket.command.dom.CreateAndAppendDOMNodeCommand.processMessage(CreateAndAppendDOMNodeCommand.java:163)
	at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:209)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by amorgner** [comment]
At first try, I'm unable to reproduce it, but from the exception stack trace, it seems that the value of `inheritVisibilityFlags` is null. I've added a check that ensures a non-null value in any case. It will be included in the next snapshot and release.

As a workaround, could you please try again with the switch "Inherit Visibility Flags" in the context menu?

![img-109](https://user-images.githubusercontent.com/291266/27196282-2108b8ba-520a-11e7-949a-8e8e91a3ce1d.jpg)

If you don't see this new menu entry after a recent update of Structr, please clear all browser caches properly and try again.

**Comment by bryonvaughn** [comment]
The checkbox was not appearing in the context menu. but clearing the cache resolved that.  Checking the box also resolved the problem I was seeing, so I'm guessing it is an artifact of using the old context menu with the new libraries.

Thanks for the quick response, and the workaround.

Best,
Bryon
