### ISSUE TITLE
Problems starting structr, Windows 10 64bit

### ISSUE THREAD

**Issue by trickidicki** [structr/structr#521]
An oldie but a goodie... Hoping for some help (not a Java guy...)

Fresh install of Structr and a fresh install of JDK 64 bit (all other Java packages uninstalled).

Thanks for the help.

```
>>where java
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe

>>java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

>>set java_home
JAVA_HOME=d:\Program Files\Java\jdk1.8.0_181
```

```
>>bin\start
D:\tools\structr-2.3.6>java -cp lib/*; org.structr.Server
15:56:02.044 [main] INFO  org.structr.Server - Starting server instance
15:56:02.054 [main] INFO  org.structr.core.app.StructrApp - Reading structr.conf..
15:56:02.131 [main] INFO  o.structr.api.service.LicenseManager - Host ID is b25c58ba6706aba087db2a3d0094a0f5
15:56:02.131 [main] INFO  o.structr.api.service.LicenseManager - Checking Structr license..
15:56:02.132 [main] INFO  o.structr.api.service.LicenseManager - Running Community Edition with modules [core, rest, ui].
15:56:02.132 [main] INFO  o.structr.api.service.LicenseManager - Evaluation License
15:56:02.734 [main] INFO  o.s.module.JarConfigurationProvider - Activating module core
15:56:02.849 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1403ms to org.eclipse.jetty.util.log.Slf4jLog
15:56:02.862 [main] INFO  o.s.module.JarConfigurationProvider - Activating module rest
15:56:03.276 [main] INFO  o.s.module.JarConfigurationProvider - Activating module ui
15:56:03.343 [main] INFO  o.s.module.JarConfigurationProvider - 28 JARs scanned
15:56:03.343 [main] INFO  org.structr.core.app.StructrApp - 4 processors available, 3 GB max heap memory
15:56:03.343 [main] WARN  org.structr.core.app.StructrApp - Maximum heap size is smaller than recommended, this can lead to problems with large databases!
15:56:03.343 [main] WARN  org.structr.core.app.StructrApp - Please configure AT LEAST 8 GBs of heap memory using -Xmx8g.
15:56:03.343 [main] INFO  org.structr.core.app.StructrApp - Starting services..
15:56:03.344 [main] INFO  org.structr.core.app.StructrApp - Creating NodeService..
15:56:06.966 [main] INFO  org.structr.bolt.BoltDatabaseService - Node cache size set to 100000
15:56:06.967 [main] INFO  org.structr.bolt.BoltDatabaseService - Relationship cache size set to 100000
15:56:06.968 [main] INFO  org.structr.core.graph.NodeService - Database driver loaded, initializing indexes..
15:56:06.984 [main] INFO  org.structr.core.graph.NodeService - Indexes successfully initialized.
15:56:07.032 [main] INFO  org.structr.core.graph.NodeService - Checking if seed file should be imported..
15:56:08.432 [main] INFO  org.structr.core.graph.NodeService - Found initial seed file and no application nodes, applying initial seed..
15:56:08.883 [main] INFO  org.structr.core.graph.SyncCommand - Imported 1 nodes and 0 rels, committing transaction..
15:56:09.426 [main] WARN  org.structr.core.graph.SyncCommand -
java.lang.NoClassDefFoundError: Could not initialize class org.structr.schema.compiler.NodeExtender
        at org.structr.schema.SchemaService.reloadSchema(SchemaService.java:103)
        at org.structr.schema.SchemaHelper.reloadSchema(SchemaHelper.java:319)
        at org.structr.core.graph.SyncCommand.importDatabase(SyncCommand.java:833)
        at org.structr.core.graph.SyncCommand.importFromStream(SyncCommand.java:339)
        at org.structr.core.graph.SyncCommand.importFromFile(SyncCommand.java:319)
        at org.structr.core.graph.SyncCommand.importFromFile(SyncCommand.java:312)
        at org.structr.core.graph.NodeService.importSeedFile(NodeService.java:203)
        at org.structr.core.graph.NodeService.initialized(NodeService.java:127)
        at org.structr.core.Services.startService(Services.java:478)
        at org.structr.core.Services.doInitialize(Services.java:227)
        at org.structr.core.Services.initialize(Services.java:186)
        at org.structr.core.Services.getInstance(Services.java:95)
        at org.structr.Server.main(Server.java:40)
15:56:09.427 [main] WARN  org.structr.core.graph.NodeService - Unable to import initial seed file.
org.structr.common.error.FrameworkException: Could not initialize class org.structr.schema.compiler.NodeExtender
        at org.structr.core.graph.SyncCommand.importFromFile(SyncCommand.java:325)
        at org.structr.core.graph.SyncCommand.importFromFile(SyncCommand.java:312)
        at org.structr.core.graph.NodeService.importSeedFile(NodeService.java:203)
        at org.structr.core.graph.NodeService.initialized(NodeService.java:127)
        at org.structr.core.Services.startService(Services.java:478)
        at org.structr.core.Services.doInitialize(Services.java:227)
        at org.structr.core.Services.initialize(Services.java:186)
        at org.structr.core.Services.getInstance(Services.java:95)
        at org.structr.Server.main(Server.java:40)
15:56:09.428 [main] INFO  org.structr.core.graph.NodeService - Done.
15:56:09.428 [main] INFO  org.structr.core.app.StructrApp - Creating AgentService..
15:56:09.429 [main] ERROR org.structr.core.app.StructrApp - Configured service AgentService is not part of the currently licensed Structr Edition.
15:56:09.429 [main] INFO  org.structr.core.app.StructrApp - Creating CronService..
15:56:09.430 [main] ERROR org.structr.core.app.StructrApp - Configured service CronService is not part of the currently licensed Structr Edition.
15:56:09.430 [main] INFO  org.structr.core.app.StructrApp - Creating SchemaService..
15:56:09.431 [main] INFO  org.structr.core.app.StructrApp - Creating HttpService..
15:56:09.432 [main] INFO  org.structr.rest.service.HttpService - Running in asynchronous mode
15:56:09.553 [main] ERROR org.structr.core.app.StructrApp - Service HttpService failed to start
java.lang.NoClassDefFoundError: Could not initialize class org.structr.schema.compiler.NodeExtender
        at org.structr.rest.service.StructrHttpServiceConfig.loadClass(StructrHttpServiceConfig.java:139)
        at org.structr.rest.service.StructrHttpServiceConfig.initializeFromSettings(StructrHttpServiceConfig.java:82)
        at org.structr.rest.service.HttpService.collectServlets(HttpService.java:596)
        at org.structr.rest.service.HttpService.initialize(HttpService.java:380)
        at org.structr.core.Services.startService(Services.java:458)
        at org.structr.core.Services.doInitialize(Services.java:227)
        at org.structr.core.Services.initialize(Services.java:186)
        at org.structr.core.Services.getInstance(Services.java:95)
        at org.structr.Server.main(Server.java:40)
15:56:09.553 [main] INFO  org.structr.core.app.StructrApp - 2 service(s) processed
15:56:09.555 [main] INFO  org.structr.core.app.StructrApp - Registering shutdown hook.
15:56:09.657 [main] WARN  org.structr.core.app.StructrApp - Exception while executing post-initialization tasks
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.structr.schema.compiler.NodeExtender
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.structr.core.Services.doInitialize(Services.java:289)
        at org.structr.core.Services.initialize(Services.java:186)
        at org.structr.core.Services.getInstance(Services.java:95)
        at org.structr.Server.main(Server.java:40)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.structr.schema.compiler.NodeExtender
        at org.structr.schema.SchemaService.reloadSchema(SchemaService.java:103)
        at org.structr.schema.SchemaService$1.initializationDone(SchemaService.java:80)
        at org.structr.core.Services$2.run(Services.java:285)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2018-08-12 15:56:09.569  ---------------- Initialization complete ----------------
```

**Comment by trickidicki** [comment]
Scratch this. As per usual, messed up Java installation... :-/
